from __future__ import annotations

from typing import Any, Protocol

from case.app.models.domain import Approval, AuditEvent, CardState, Case, CaseNote, Notification


class CaseRepository(Protocol):
    async def create(self, value: Case) -> Case: ...
    async def get(self, case_id: str) -> Case: ...
    async def update(self, value: Case) -> Case: ...
    async def search(self, filters: dict[str, Any], limit: int) -> list[Case]: ...
    async def find_unique(self, fraud_alert_id: str | None, idempotency_key: str | None) -> Case | None: ...


class CaseNoteRepository(Protocol):
    async def create(self, value: CaseNote) -> CaseNote: ...
    async def list(self, case_id: str, limit: int) -> list[CaseNote]: ...


class ApprovalRepository(Protocol):
    async def create(self, value: Approval) -> Approval: ...
    async def get(self, approval_id: str) -> Approval: ...
    async def update(self, value: Approval) -> Approval: ...
    async def list(self, case_id: str) -> list[Approval]: ...
    async def find_pending(self, case_id: str, action_type: str, idempotency_key: str | None) -> Approval | None: ...


class CardStateRepository(Protocol):
    async def get(self, card_id: str) -> CardState: ...
    async def upsert(self, value: CardState) -> CardState: ...


class NotificationRepository(Protocol):
    async def create(self, value: Notification) -> Notification: ...
    async def list(self, case_id: str) -> list[Notification]: ...
    async def find_idempotent(self, key: str) -> Notification | None: ...


class AuditRepository(Protocol):
    async def append(self, value: AuditEvent) -> AuditEvent: ...
    async def list(self, case_id: str, limit: int) -> list[AuditEvent]: ...
